#define VER_FILESERIALVERSION 0000
#define VER_PRODUCTVERSION 8,5,0000,0
#define VER_COMPANYNAME_STR "Kontron Europe GmbH\0"
#define VER_LEGALCOPYRIGHT_STR "(c) 2026 Kontron Europe GmbH\0"
#define VER_PRODUCTNAME_STR "GABI_ACPI\0"
#define VER_PRODUCTVERSION_STR "8.5.0000.0\0"
#ifdef _WIN64
#define VER_PLATFORMAPPEND " (64 bit)"
#else
#define VER_PLATFORMAPPEND ""
#endif
