//
// PIIX4, ICHx and compatible - SMBus
//

// SMBus Register
#define SMBUS_HOST_STATUS_REGISTER		0x00
#define SMBUS_SLAVE_STATUS_REGISTER		0x01
#define SMBUS_HOST_CONTROL_REGISTER		0x02
#define SMBUS_HOST_COMMAND_REGISTER		0x03
#define SMBUS_HOST_ADDRESS_REGISTER		0x04
#define SMBUS_HOST_DATA0_REGISTER		0x05
#define SMBUS_HOST_DATA1_REGISTER		0x06
#define SMBUS_HOST_BLOCKDATA_REGISTER	0x07


// HST_STA Host Status Register (Offset 00h)
#define SMBUS_HST_STA_BYTE_DONE_STS		0x80	// NO PIIX4 SUPPORT!!!
#define SMBUS_HST_STA_INUSE_STS			0x40	// NO PIIX4 SUPPORT!!!
#define SMBUS_HST_STA_SMBALERT_STS		0x20	// NO PIIX4 SUPPORT!!!
#define SMBUS_HST_STA_FAILED			0x10
#define SMBUS_HST_STA_BUS_ERR			0x08
#define SMBUS_HST_STA_DEV_ERR			0x04
#define SMBUS_HST_STA_INTR				0x02
#define SMBUS_HST_STA_HOST_BUSY			0x01
#define SMBUS_HST_STA_INT_MASK			(SMBUS_HST_STA_INTR | SMBUS_HST_STA_DEV_ERR | SMBUS_HST_STA_BUS_ERR | \
										 SMBUS_HST_STA_FAILED | SMBUS_HST_STA_SMBALERT_STS | SMBUS_HST_STA_BYTE_DONE_STS)

// HST_CNT Host Control Register (Offset 02h)
#define SMBUS_HST_CNT_START				0x40
#define SMBUS_HST_CNT_LAST_BYTE			0x20	// NO PIIX4 SUPPORT!!
#define SMBUS_HST_CNT_CMD_QUICK			(0<<2)
#define SMBUS_HST_CNT_CMD_BYTE			(1<<2)
#define SMBUS_HST_CNT_CMD_BYTE_DATA		(2<<2)
#define SMBUS_HST_CNT_CMD_WORD_DATA		(3<<2)
#define SMBUS_HST_CNT_CMD_PROCESS_CALL	(4<<2)	// NO PIIX4 SUPPORT!!
#define SMBUS_HST_CNT_CMD_BLOCK			(5<<2)
#define SMBUS_HST_CNT_CMD_I2C_READ		(6<<2)	// NO PIIX4 SUPPORT!!
#define SMBUS_HST_CNT_CMD_RESERVED		(7<<2)
#define SMBUS_HST_CNT_KILL				0x02
#define SMBUS_HST_CNT_INTREN			0x01

